// File: Resources.h
// NOTE: This file auto generated by BuildResources.exe - Do not edit by hand!
//
#if !defined(__RESOURCES_H__)
#define __RESOURCES_H__

// Bitmap File: bitmaps/red_square.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[10000];
} red_square_T;
extern const red_square_T red_square;

// Bitmap File: bitmaps/lighting_bar.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[27000];
} lighting_bar_T;
extern const lighting_bar_T lighting_bar;

// Bitmap File: bitmaps/up.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} up_T;
extern const up_T up;

// Bitmap File: bitmaps/up_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} up_s_T;
extern const up_s_T up_s;

// Bitmap File: bitmaps/down.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} down_T;
extern const down_T down;

// Bitmap File: bitmaps/down_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} down_s_T;
extern const down_s_T down_s;

// Bitmap File: bitmaps/left.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} left_T;
extern const left_T left;

// Bitmap File: bitmaps/left_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} left_s_T;
extern const left_s_T left_s;

// Bitmap File: bitmaps/right.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} right_T;
extern const right_T right;

// Bitmap File: bitmaps/right_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} right_s_T;
extern const right_s_T right_s;

// Bitmap File: bitmaps/lighting_ico.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lighting_ico_T;
extern const lighting_ico_T lighting_ico;

// Bitmap File: bitmaps/lighting_ico_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lighting_ico_s_T;
extern const lighting_ico_s_T lighting_ico_s;

// Bitmap File: bitmaps/back.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} back_T;
extern const back_T back;

// Bitmap File: bitmaps/back_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} back_s_T;
extern const back_s_T back_s;

// Bitmap File: bitmaps/blank.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} blank_T;
extern const blank_T blank;

// Bitmap File: bitmaps/blank_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} blank_s_T;
extern const blank_s_T blank_s;

// Bitmap File: bitmaps/key_light_minus.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} key_light_minus_T;
extern const key_light_minus_T key_light_minus;

// Bitmap File: bitmaps/key_light_plus.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} key_light_plus_T;
extern const key_light_plus_T key_light_plus;

// Bitmap File: bitmaps/key_light_minus_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} key_light_minus_s_T;
extern const key_light_minus_s_T key_light_minus_s;

// Bitmap File: bitmaps/key_light_plus_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} key_light_plus_s_T;
extern const key_light_plus_s_T key_light_plus_s;

// Bitmap File: bitmaps/lcd_light_minus.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lcd_light_minus_T;
extern const lcd_light_minus_T lcd_light_minus;

// Bitmap File: bitmaps/lcd_light_plus.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lcd_light_plus_T;
extern const lcd_light_plus_T lcd_light_plus;

// Bitmap File: bitmaps/lcd_light_minus_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lcd_light_minus_s_T;
extern const lcd_light_minus_s_T lcd_light_minus_s;

// Bitmap File: bitmaps/lcd_light_plus_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lcd_light_plus_s_T;
extern const lcd_light_plus_s_T lcd_light_plus_s;

// Bitmap File: bitmaps/blank64wide.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[2048];
} blank64wide_T;
extern const blank64wide_T blank64wide;

// Bitmap File: bitmaps/blank64wide_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[2048];
} blank64wide_s_T;
extern const blank64wide_s_T blank64wide_s;

// Bitmap File: bitmaps/view_meters.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} view_meters_T;
extern const view_meters_T view_meters;

// Bitmap File: bitmaps/1.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} one_T;
extern const one_T one;

// Bitmap File: bitmaps/2.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} two_T;
extern const two_T two;

// Bitmap File: bitmaps/3.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} three_T;
extern const three_T three;

// Bitmap File: bitmaps/toggle.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} toggle_T;
extern const toggle_T toggle;

// Bitmap File: bitmaps/thrust_calib.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} thrust_calib_T;
extern const thrust_calib_T thrust_calib;

// Bitmap File: bitmaps/init_cal.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} init_cal_T;
extern const init_cal_T init_cal;

// Bitmap File: bitmaps/init_zthrust.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} init_zthrust_T;
extern const init_zthrust_T init_zthrust;

// Bitmap File: bitmaps/init_transmit.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} init_transmit_T;
extern const init_transmit_T init_transmit;

// Bitmap File: bitmaps/set_zthrust.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} set_zthrust_T;
extern const set_zthrust_T set_zthrust;

// Bitmap File: bitmaps/set_transmit.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} set_transmit_T;
extern const set_transmit_T set_transmit;

// Bitmap File: bitmaps/finish_calib.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} finish_calib_T;
extern const finish_calib_T finish_calib;

// Bitmap File: bitmaps/abort_calib.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} abort_calib_T;
extern const abort_calib_T abort_calib;

// Bitmap File: bitmaps/warning.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[1024];
} warning_T;
extern const warning_T warning;

// Bitmap File: bitmaps/alarm_ack.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} alarm_ack_T;
extern const alarm_ack_T alarm_ack;

// Bitmap File: bitmaps/calib_screen.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} calib_screen_T;
extern const calib_screen_T calib_screen;

// Bitmap File: bitmaps/fault_screen.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} fault_screen_T;
extern const fault_screen_T fault_screen;

// Bitmap File: bitmaps/system_screen.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} system_screen_T;
extern const system_screen_T system_screen;

// Bitmap File: bitmaps/exit.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} exit_menu_T;
extern const exit_menu_T exit_menu;

// Font File: ttfnt/LiberationSans.ttf
extern const unsigned int TTFONT_MAIN_SIZE;
extern const unsigned char TTFONT_MAIN[];

// Font File: ttfnt/LiberationMono.ttf
extern const unsigned int TTFONT_MONOSPACE_SIZE;
extern const unsigned char TTFONT_MONOSPACE[];

#endif // #if !defined(__RESOURCES_H__)
