// File: Resources.h
// NOTE: This file auto generated by BuildResources.exe - Do not edit by hand!
//
#if !defined(__RESOURCES_H__)
#define __RESOURCES_H__

// Bitmap File: bitmaps/red_square.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[10000];
} red_square_T;
extern const red_square_T red_square;

// Bitmap File: bitmaps/lighting_bar.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[27000];
} lighting_bar_T;
extern const lighting_bar_T lighting_bar;

// Bitmap File: bitmaps/up.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} up_T;
extern const up_T up;

// Bitmap File: bitmaps/up_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} up_s_T;
extern const up_s_T up_s;

// Bitmap File: bitmaps/down.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} down_T;
extern const down_T down;

// Bitmap File: bitmaps/down_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} down_s_T;
extern const down_s_T down_s;

// Bitmap File: bitmaps/left.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} left_T;
extern const left_T left;

// Bitmap File: bitmaps/left_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} left_s_T;
extern const left_s_T left_s;

// Bitmap File: bitmaps/right.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} right_T;
extern const right_T right;

// Bitmap File: bitmaps/right_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} right_s_T;
extern const right_s_T right_s;

// Bitmap File: bitmaps/lighting_ico.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lighting_ico_T;
extern const lighting_ico_T lighting_ico;

// Bitmap File: bitmaps/lighting_ico_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lighting_ico_s_T;
extern const lighting_ico_s_T lighting_ico_s;

// Bitmap File: bitmaps/back.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} back_T;
extern const back_T back;

// Bitmap File: bitmaps/back_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} back_s_T;
extern const back_s_T back_s;

// Bitmap File: bitmaps/blank.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} blank_T;
extern const blank_T blank;

// Bitmap File: bitmaps/blank_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} blank_s_T;
extern const blank_s_T blank_s;

// Bitmap File: bitmaps/key_light_minus.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} key_light_minus_T;
extern const key_light_minus_T key_light_minus;

// Bitmap File: bitmaps/key_light_plus.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} key_light_plus_T;
extern const key_light_plus_T key_light_plus;

// Bitmap File: bitmaps/key_light_minus_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} key_light_minus_s_T;
extern const key_light_minus_s_T key_light_minus_s;

// Bitmap File: bitmaps/key_light_plus_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} key_light_plus_s_T;
extern const key_light_plus_s_T key_light_plus_s;

// Bitmap File: bitmaps/lcd_light_minus.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lcd_light_minus_T;
extern const lcd_light_minus_T lcd_light_minus;

// Bitmap File: bitmaps/lcd_light_plus.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lcd_light_plus_T;
extern const lcd_light_plus_T lcd_light_plus;

// Bitmap File: bitmaps/lcd_light_minus_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lcd_light_minus_s_T;
extern const lcd_light_minus_s_T lcd_light_minus_s;

// Bitmap File: bitmaps/lcd_light_plus_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[3072];
} lcd_light_plus_s_T;
extern const lcd_light_plus_s_T lcd_light_plus_s;

// Bitmap File: bitmaps/blank64wide.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[2048];
} blank64wide_T;
extern const blank64wide_T blank64wide;

// Bitmap File: bitmaps/blank64wide_s.png
typedef struct
{
    unsigned char nb_layer;
    unsigned int x;
    unsigned int y;
    unsigned short bitmap[2048];
} blank64wide_s_T;
extern const blank64wide_s_T blank64wide_s;

// Font File: ttfnt/LiberationSans.ttf
extern const unsigned int TTFONT_MAIN_SIZE;
extern const unsigned char TTFONT_MAIN[];

// Font File: ttfnt/LiberationMono.ttf
extern const unsigned int TTFONT_MONOSPACE_SIZE;
extern const unsigned char TTFONT_MONOSPACE[];

#endif // #if !defined(__RESOURCES_H__)
